### ISSUE TITLE
JOINTLYsolve - Sparse -> dense coercion 

### ISSUE THREAD

**Issue by RolantusdataExp** [madsen-lab/rJOINTLY#1]
Hi Madsen-lab, 
Thanks for the tool!
During the JOINTLYsolve step (function), it seems like the function performs a Sparse -> Dense coercion. May I suggest changing this function to avoid this coercion, and improve memory util. 

Best regards,

**Comment by JesperGrud** [comment]
Thank you for your suggestion. Currently, the package environment for solving NMF does not support sparse matrix, but we will keep your suggestion in mind if that changes.
